# Generated by Django 4.1.4 on 2022-12-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_location',
            field=models.CharField(max_length=500),
        ),
    ]
